input_boolean:
  kiss_hyperspace:
    name: Kiss Hyperspace
    icon: mdi:rocket-launch

script:
  kiss_hue_blink_rot:
    alias: "KISS | Hue blinkt rot"
    mode: restart
    sequence:
      - repeat:
          count: 5
          sequence:
            - service: light.turn_on
              target:
                entity_id: light.hue_alle
              data:
                color_name: red
                brightness_pct: 100
                transition: 0
            - delay: "00:00:01"
            - service: light.turn_off
              target:
                entity_id: light.hue_alle
            - delay: "00:00:01"

  kiss_master_sequence:
    alias: "KISS | Master Sequence"
    mode: restart
    sequence:
      - service: script.turn_on
        target:
          entity_id: script.kiss_hue_blink_rot

      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.kiss_hyperspace

      - delay: "00:01:00"

      - service: notify.mobile_app_bruce_wayne
        data:
          title: "ðŸ’‹ KISS"
          message: "Ich lieb di so hart"

      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.kiss_hyperspace
