esphome:
  name: test
  friendly_name: test

rp2040:
  board: rpipicow

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "ZiSH4cSy1vwHmiAjjpkkA4PmxTgSSDMiZ/d4QJGSOSE="

ota:
  - platform: esphome
    password: "8e4d9f483c7718c6d20ddc922c8706a0"

wifi:
  ssid: webworldwide
  password: titleist
  

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "Test Fallback Hotspot"
    password: "y4uSvv9VZZvT"
    